#pragma once

#define APP_WIFI_SSID            CONFIG_APP_WIFI_SSID
#define APP_WIFI_PASSWORD        CONFIG_APP_WIFI_PASSWORD

#define APP_OTA_FIRMWARE_URL     CONFIG_APP_OTA_FIRMWARE_URL
#define APP_OTA_TRIGGER_URL      CONFIG_APP_OTA_TRIGGER_URL

#define APP_OTA_ALLOW_NO_TIME    CONFIG_APP_OTA_ALLOW_WITHOUT_TIME
#define APP_OTA_MAINT_START_HOUR CONFIG_APP_OTA_MAINT_START_HOUR
#define APP_OTA_MAINT_END_HOUR   CONFIG_APP_OTA_MAINT_END_HOUR

#define APP_BATT_MIN_MV          CONFIG_APP_BATT_MIN_MV
#define APP_BATT_FAKE_MV         CONFIG_APP_BATT_FAKE_MV

#define APP_OTA_BUTTON_GPIO      CONFIG_APP_OTA_BUTTON_GPIO
#define APP_OTA_POLL_PERIOD_MS   CONFIG_APP_OTA_POLL_PERIOD_MS